# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"2\n\rVolumeRequest\x12\x0e\n\x06volume\x18\x01 \x01(\x02\x12\x11\n\tflow_rate\x18\x02 \x01(\x02\"\"\n\x0eVolumeResponse\x12\x10\n\x08\x64uration\x18\x01 \x01(\x02\"%\n\x11MonitoringRequest\x12\x10\n\x08\x64uration\x18\x01 \x01(\x02\"^\n\x10RecordingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0creal_glucose\x18\x02 \x01(\x02\x12\x14\n\x0creal_lactate\x18\x03 \x01(\x02\x12\x10\n\x08\x64uration\x18\x04 \x01(\x02\"R\n\x0bMeasurement\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x17\n\x0fglucose_current\x18\x02 \x01(\x02\x12\x17\n\x0flactate_current\x18\x03 \x01(\x02\x32\xa0\x01\n\rGlucoseSensor\x12/\n\npump_it_up\x12\x0e.VolumeRequest\x1a\x0f.VolumeResponse\"\x00\x12/\n\x07monitor\x12\x12.MonitoringRequest\x1a\x0c.Measurement\"\x00\x30\x01\x12-\n\x06record\x12\x11.RecordingRequest\x1a\x0c.Measurement\"\x00\x30\x01\x62\x06proto3')



_VOLUMEREQUEST = DESCRIPTOR.message_types_by_name['VolumeRequest']
_VOLUMERESPONSE = DESCRIPTOR.message_types_by_name['VolumeResponse']
_MONITORINGREQUEST = DESCRIPTOR.message_types_by_name['MonitoringRequest']
_RECORDINGREQUEST = DESCRIPTOR.message_types_by_name['RecordingRequest']
_MEASUREMENT = DESCRIPTOR.message_types_by_name['Measurement']
VolumeRequest = _reflection.GeneratedProtocolMessageType('VolumeRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOLUMEREQUEST,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:VolumeRequest)
  })
_sym_db.RegisterMessage(VolumeRequest)

VolumeResponse = _reflection.GeneratedProtocolMessageType('VolumeResponse', (_message.Message,), {
  'DESCRIPTOR' : _VOLUMERESPONSE,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:VolumeResponse)
  })
_sym_db.RegisterMessage(VolumeResponse)

MonitoringRequest = _reflection.GeneratedProtocolMessageType('MonitoringRequest', (_message.Message,), {
  'DESCRIPTOR' : _MONITORINGREQUEST,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:MonitoringRequest)
  })
_sym_db.RegisterMessage(MonitoringRequest)

RecordingRequest = _reflection.GeneratedProtocolMessageType('RecordingRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECORDINGREQUEST,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:RecordingRequest)
  })
_sym_db.RegisterMessage(RecordingRequest)

Measurement = _reflection.GeneratedProtocolMessageType('Measurement', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENT,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:Measurement)
  })
_sym_db.RegisterMessage(Measurement)

_GLUCOSESENSOR = DESCRIPTOR.services_by_name['GlucoseSensor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOLUMEREQUEST._serialized_start=16
  _VOLUMEREQUEST._serialized_end=66
  _VOLUMERESPONSE._serialized_start=68
  _VOLUMERESPONSE._serialized_end=102
  _MONITORINGREQUEST._serialized_start=104
  _MONITORINGREQUEST._serialized_end=141
  _RECORDINGREQUEST._serialized_start=143
  _RECORDINGREQUEST._serialized_end=237
  _MEASUREMENT._serialized_start=239
  _MEASUREMENT._serialized_end=321
  _GLUCOSESENSOR._serialized_start=324
  _GLUCOSESENSOR._serialized_end=484
# @@protoc_insertion_point(module_scope)
